kind: pipeline
name: default

steps:
- name: login
  image: docker
  commands:
  # install awscli
  - apk --update add python3 && pip3 install awscli
  # login to ecr
  - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
  # pull private images
  - docker pull 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com/test-image
  volumes:
  - name: docker
    path: /var/run/docker.sock


- name: run
  image: 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com/test-image
  pull: never
  detach: true
  volumes:
  - name: root
    path: /root

# to mount host volumes requires to be trusted
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
