kind: pipeline
name: default

steps:
- name: build
  image: golang:1.10
  steps:
  - go build

- name: docker login
  image: alpine
  steps:
  - eval $(aws ecr get-login --no-include-email --region ap-northeast-1)
  - ls ~/.docker
  - cat ~/.docker/config.json

- name: docker  
  image: plugins/ecr
  settings:
    registry: 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com
    repo: 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com/test-image
    tags:
    - latest