kind: pipeline
name: default

steps:
- name: build
  image: golang:1.10
  steps:
  - go build

- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com/test-image
    tags: latest