kind: pipeline
name: default

steps:
- name: build
  image: golang:1.10
  steps:
  - go build

- name: docker  
  image: plugins/docker
  settings:
    registry: 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com
    repo: 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com/test-image
    username:
      from_secret: dockerusername
    password:
      from_secret: dockerpassword
    tags:
    - latest