kind: pipeline
name: default

steps:
- name: login
  image: docker
  commands:
  - apk --update add python curl
  - wget -O get-pip.py 'https://bootstrap.pypa.io/get-pip.py'
  - python get-pip.py --disable-pip-version-check --no-cache-dir
  - pip install awscli
  - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
  - ls -al /root
  - ls -al /root/.docker
  - cat /root/.docker/config.json
  - docker pull 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com/test-image
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: run
  image: 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com/test-image
  pull: never
  detach: true
  volumes:
  - name: root
    path: /root

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
