kind: pipeline
name: default

steps:
- name: build
  image: golang:1.10
  commands:
  - go test -v ./...
  - go build

- name: login
  image: python:3.7
  commands:
  - pip3 install awscli --upgrade
  - aws --version
  - aws ecr get-login --no-include-email --region ap-northeast-1
  - eval $(aws ecr get-login --no-include-email --region ap-northeast-1)

- name: docker  
  image: plugins/ecr
  settings:
    registry: 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com
    repo: 706429988202.dkr.ecr.ap-northeast-1.amazonaws.com/test-image
    tags:
    - latest